FROM depage/php-5.6
MAINTAINER ${MAINTAINER}

ADD rootfs.tar /

RUN useradd -s /bin/false -u 101 -c "added by dockerfile for php-fpm" -d /var/www/ www-data && \
    if [ ! -f /usr/bin/php ]; then ln -s /usr/bin/php5.6 /usr/bin/php; fi && \
    curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/bin/composer
