FROM gentoobb/openssl
MAINTAINER ${MAINTAINER}

ADD rootfs.tar /

ADD etc /etc

RUN chmod +x $(find /etc/service -name run) && ln -s /etc/service/php-fpm /service && \
    if [ ! -f /usr/bin/php ]; then ln -s /usr/bin/php5.6 /usr/bin/php; fi && \
    curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/bin/composer
